package com.healthcompanion.service;
import com.healthcompanion.dto.WellnessDtos.*; import com.healthcompanion.entity.*; import com.healthcompanion.repository.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service public class WellnessService { private final WellnessEntryRepository entries; private final WellnessAnalysisRepository analyses; private final UserService users; public WellnessService(WellnessEntryRepository e,WellnessAnalysisRepository a,UserService u){entries=e;analyses=a;users=u;}
 @Transactional public SummaryResponse checkIn(String email,CheckInRequest r){User u=users.current(email);WellnessEntry e=new WellnessEntry();e.setUser(u);e.setMood(r.mood());e.setStress(r.stress());e.setEnergy(r.energy());e.setSleepHours(r.sleepHours());e.setJournalText(r.journalText());entries.save(e);return summary(email);}
 public List<EntryResponse> history(String email){return entries.findTop30ByUserOrderByCreatedAtDesc(users.current(email)).stream().map(EntryResponse::from).toList();}
 public SummaryResponse summary(String email){User u=users.current(email);List<WellnessEntry> list=entries.findTop30ByUserOrderByCreatedAtDesc(u);double mood=avg(list,1),stress=avg(list,2),energy=avg(list,3),sleep=avg(list,4);WellnessAnalysis a=analyses.findTopByUserOrderByCreatedAtDesc(u).orElse(null);return new SummaryResponse(list.stream().map(EntryResponse::from).toList(),a==null?null:AnalysisResponse.from(a),mood,stress,energy,sleep);}
 private double avg(List<WellnessEntry> l,int field){if(l.isEmpty())return 0;return Math.round(l.stream().mapToDouble(e->field==1?e.getMood():field==2?e.getStress():field==3?e.getEnergy():e.getSleepHours()).average().orElse(0)*10)/10.0;}
 @Transactional public AnalysisResponse analyze(String email){User u=users.current(email);List<WellnessEntry> l=entries.findTop30ByUserOrderByCreatedAtDesc(u);if(l.isEmpty())return null;double mood=avg(l,1),stress=avg(l,2),sleep=avg(l,4);WellnessAnalysis a=new WellnessAnalysis();a.setUser(u);a.setMoodTrend(mood>=6?"Stable / positive":"Lower recently");a.setStressTrend(stress<=4?"Lower recently":"Higher recently");a.setSleepTrend(sleep>=7?"Steady":"Slightly reduced");a.setAnalysis("Your recent self-reported entries show mood at "+mood+"/10, stress at "+stress+"/10 and average sleep of "+sleep+" hours. These are personal trends, not a diagnosis. If changes continue or affect daily life, consider talking with someone you trust or a qualified professional.");return AnalysisResponse.from(analyses.save(a));}
}
